defaults: &defaults
  app:
    title: CadCam

    asset_host: http://cadcam.chebytoday.ru/

    default_url_options: &default_url_options
      host: cadcam.chebytoday.ru
      port: 80

  action_mailer: &action_mailer
    raise_delivery_errors: false
    default_url_options:
      <<: *default_url_options

  mailer_defaults: &mailer_defaults
    from: 'noreply@chebytoday.ru'
    host: cadcam.chebytoday.ru

development:
  <<: *defaults
  action_mailer:
    <<: *action_mailer
    delivery_method: :smtp
    smtp_settings:
      address: localhost
      port: 1025   # mailcatcher
    raise_delivery_errors: true

test:
  <<: *defaults
  capybara:
    port: 57500

  mailer_defaults:
    <<: *mailer_defaults

  action_mailer:
    <<: *action_mailer
    delivery_method: :test

production:
  <<: *defaults
  mailer_defaults:
    <<: *mailer_defaults

staging:
  <<: *defaults
  mailer_defaults:
    <<: *mailer_defaults

